runtime: nodejs8

env_variables:
  BOTFUEL_APP_TOKEN: "1409617952378"
  BOTFUEL_APP_ID: "3e8fea28"
  BOTFUEL_APP_KEY: "0ba9b171e85bfe07c56f10f6fc1749da"
  WEATHER_API_KEY: "9b7a7201fbf64c56ace100508181008"

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  forwarded_ports:
    - 8080
